# Generated by Django 5.0.4 on 2024-04-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal",
                    models.CharField(
                        choices=[("B", "Breakfast"), ("L", "Lunch"), ("D", "Dinner")],
                        default="B",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
