# Generated by Django 5.0.4 on 2024-04-25 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_feeding"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeding",
            name="finch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.finch",
            ),
            preserve_default=False,
        ),
    ]
