# Generated by Django 5.0.4 on 2024-04-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_feeding_finch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeding",
            name="finch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.finch",
            ),
        ),
    ]
